import os
from pidng.core import RPICAM2DNG

MARGIN = 10
SCREEN_W = 480
SCREEN_H = 320
UPDATE_DELAY = 30
DISPLAY_W = 480
DISPLAY_H = 320
G_INFO_H = 45
G_META_W = 201
G_META_H = 17
G_PREVIEW_H = SCREEN_H - G_INFO_H
G_PREVIEW_W = int(G_PREVIEW_H * 4 / 3)
DCIM = os.path.expanduser("~/DCIM")
DNG = RPICAM2DNG()
CAM_NAME = "LYY&HZ Camera"
BG_COLOR = "#000"
BORDER_COLOR = "#444"
BUTTON_COLOR = "#222"
INFO_COLOR = "#222"
BUTTON_ACTIVE_COLOR = "#1a1a1a"
BUTTON_WARN_COLOR = "#cc1504"
TEXT_COLOR = "#fff"
